### ISSUE TITLE
FileSystem.SYSTEM is missing in okio-common now. Is it expected?

### ISSUE THREAD

**Issue by akuleshov7** [square/okio#1070]
I can still see it in jvm, but it looks like this change in API was intended.
What was the idea behind this solution?

**Comment by JakeWharton** [comment]
Yes. There is no system file system in the browser.

**Comment by akuleshov7** [comment]
But may be it will be better to mock JS with NotImplemented?

**Comment by JakeWharton** [comment]
If you do not have a JS source set the commonizer should make `SYSTEM` available to your `commonMain`. If you do have JS, then you need to decide how your application behaves on that platform.

Also, notably, the filesystem API does not work in the browser because all of the browser file system APIs are asynchronous. It only works when run with NodeJS.

**Comment by akuleshov7** [comment]
Got it, thanks

**Comment by nbransby** [comment]
@akuleshov7 do did you solve this? I do not have a JS source set and the commonizer does not appear make SYSTEM available to  commonMain

**Comment by elect86** [comment]
Similar here, jvm and native, but still no `SYSTEM` available..
