### ISSUE TITLE
Cannot open executable Zip files.

### ISSUE THREAD

**Issue by oldergod** [square/okio#1094]
Looks like Spring creates [executable jars](https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html) which Okio fails to open.

```
Caused by: java.io.IOException: not a zip: expected 0x4034b50 but was 0x622f2123
	at okio.internal.ZipKt.openZip(zip.kt:75) ~[okio-jvm-3.0.0.jar!/:na]
	at okio.internal.ResourceFileSystem$Companion.toJarRoot(ResourceFileSystem.kt:201) ~[okio-jvm-3.0.0.jar!/:na]
	at okio.internal.ResourceFileSystem$Companion.toClasspathRoots(ResourceFileSystem.kt:184) ~[okio-jvm-3.0.0.jar!/:na]
	at okio.internal.ResourceFileSystem$roots$2.invoke(ResourceFileSystem.kt:47) ~[okio-jvm-3.0.0.jar!/:na]
	at okio.internal.ResourceFileSystem$roots$2.invoke(ResourceFileSystem.kt:47) ~[okio-jvm-3.0.0.jar!/:na]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[kotlin-stdlib-1.4.30.jar!/:1.4.30-release-302 (1.4.30)]
	at okio.internal.ResourceFileSystem.getRoots(ResourceFileSystem.kt:47) ~[okio-jvm-3.0.0.jar!/:na]
	at okio.internal.ResourceFileSystem.source(ResourceFileSystem.kt:126) ~[okio-jvm-3.0.0.jar!/:na]
	at com.squareup.wire.schema.CoreLoader.load(CoreLoader.kt:79) ~[wire-schema-jvm-4.1.0.jar!/:na]
```

See https://github.com/square/wire/discussions/2209

**Comment by martypitt** [comment]
Hi - I'm the OP on the original issue.

I've tried a couple of things on this one, but haven't found any success.

## Made the spring boot jar non executable.
```
<plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <executable>false</executable>
                </configuration>
```

This at least removes the `not a zip:` error.
However, I quickly fall at the next hurdle.

## Export the dependencies explicitly
Turns out that the Spring Boot plugin will allow you to make [specific jars explicitly available](https://docs.spring.io/spring-boot/docs/1.4.x/reference/htmlsingle/#howto-extract-specific-libraries-when-an-executable-jar-runs) in the fat jar. 

This kinda worked - for the JARs I explicitly exported, it looks like the ResourceFileSystem loaded them successfully.  But it looks CoreLoader is iterating over every jar in the classpath, and throws NullPointer exceptions when the file isn't available.  

Given `ResourceFileSystem` declares the following:

```
fun URL.toJarRoot(): Pair<FileSystem, Path>? {
      val urlString = toString()
      if (!urlString.startsWith("jar:file:")) return null // Ignore unexpected URLs.
...
```

A possible alternative is that if the file is not found, to log and return null.  This would at least allow loading to continue.

## Use different Spring Boot layouts
Spring boot let us change the [layout](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#goals-repackage-parameters-details-layout).

I've tried all the options, and all threw FileNotFound exceptions:

```
Caused by: java.io.FileNotFoundException: /home/martypitt/dev/vyne-demos/films/films-api/target/films-api.jar!/BOOT-INF/lib/films-kafka-publisher-0.1.0-SNAPSHOT.jar (No such file or directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method) ~[na:na]
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345) ~[na:na]
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259) ~[na:na]
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214) ~[na:na]
	at okio.JvmSystemFileSystem.openReadOnly(JvmSystemFileSystem.kt:82) ~[okio-jvm-3.0.0.jar!/:na]
	at okio.internal.ZipKt.openZip(zip.kt:67) ~[okio-jvm-3.0.0.jar!/:na]
	at okio.internal.ResourceFileSystem$Companion.toJarRoot(ResourceFileSystem.kt:201) ~[okio-jvm-3.0.0.jar!/:na]
	at okio.internal.ResourceFileSystem$Companion.toClasspathRoots(ResourceFileSystem.kt:184) ~[okio-jvm-3.0.0.jar!/:na]
```

So, still a bit stuck, but thought I'd share the progress / research.

**Comment by swankjesse** [comment]
I think we should skip malformed and unreadable files.

**Comment by JakeWharton** [comment]
Talked with Benoît about this a bit when the issue was first filed. There are still Okio bugs here.

The first bytes are not guaranteed to be `0x4034b50`. They can be anything as the zip format allows arbitrary data anywhere except at the end. From Wikipedia:

> ZIP archives can also include extra data that is not related to the ZIP archive. This allows for a ZIP archive to be made into a self-extracting archive (application that decompresses its contained data), by prepending the program code to a ZIP archive and marking the file as executable. Storing the catalog at the end also makes possible hiding a zipped file by appending it to an innocuous file, such as a GIF image file.

and 

> There is no BOF or EOF marker in the ZIP specification. Conventionally the first thing in a ZIP file is a ZIP entry, which can be identified easily by its local file header signature. However, this is not necessarily the case, as this not required by the ZIP specification - most notably, a self-extracting archive will begin with an executable file header.

Additionally, the code assumes that if the first bytes of the zip are the central directory then the zip is empty. But based on the above details there can be any amount of arbitrary data (and even valid zip entries which are not in the central directory) which appear before it.

I _think_ all that's needed is to remove the first bytes check and move the empty check to after the central directory has been read by switching it to read the count.

**Comment by swankjesse** [comment]
Agreed that we should relax our decoder and rely on the central directory exclusively.

Our decoding behavior is consistent with Android’s ZipInputStream, which I used as a reference.

https://android.googlesource.com/platform/libcore/+/refs/heads/ics-mr1/luni/src/main/java/java/util/zip/ZipInputStream.java

I suspect it's also true of the JVM’s ZipInputStream, which can't read the central directory first either.

https://stackoverflow.com/questions/7924895/how-can-i-read-from-a-winzip-self-extracting-exe-zip-file-in-java

It's also consistent with section 4.3.6 of the zip spec. The spec also discusses self-extracting, though it's surprising - it expects a `filename.exe` entry for the extractor program.

https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

**Comment by JakeWharton** [comment]
Both Android and Java's `ZipInputStream` do not read the central directory because they are single-pass. They will return entries which aren't even mentioned in the central directory. I do not think they are the best types to emulate behaviorally because Okio is not single-pass, it's random access.

I suspect Java's random-access-supporting `ZipFile` handles it and I'm certain that its `java.nio.path.FileSystem` zip support correctly handles them. Diffuse, a self-executing jar, can read its own jar using `j.n.p.FileSystem`.

I'm pretty sure the Spring jars and definitely jars like Diffuse are not self-extracting but rather leverage the ability to prepend data to change the type of file when read from font-to-back (e.g., shell script) as opposed to when read from the back (zip file).

**Comment by gigi** [comment]
Hi! I see that this issue is closed. So, could you please provide solution to fix `Caused by: java.io.FileNotFoundException` when running Spring app within jar? 

More details here
https://github.com/square/wire/discussions/2209#discussioncomment-2587999

Thanx
