### ISSUE TITLE
Add `okio-jvm` to the `okio-bom`

### ISSUE THREAD

**Issue by rickie** [square/okio#1121]
We are working on the upgrade of `okio` and decided to use the `okio-bom`. 
As we are using Maven, we also had to switch to `okio-jvm` (see related issue https://github.com/square/okio/issues/1067).

However, now that we switched to the BOM, we also had to specify the `okio-jvm` dependency to make sure it uses the same version as in the `okio-bom`.
Would it be possible to add the `okio-jvm` in the `okio-bom` such that the dependency is provided "out of the box"?

**Comment by bogdandrutu** [comment]
Can this be fixed please?

**Comment by Stephan202** [comment]
Hey @Egorand! This issue is still relevant for users of the [maven-dependency-plugin](https://maven.apache.org/plugins/maven-dependency-plugin/analyze-only-mojo.html), as explicit references to a dependency require said dependency to be declared explicitly:
```
[INFO] --- dependency:3.5.0:analyze-only (analyze-dependencies) @ messaging-support ---
[ERROR] Used undeclared dependencies found:
[ERROR]    com.squareup.okio:okio-jvm:jar:3.3.0:runtime
```

So it'd be nice if `okio-jvm` can be added to `okio-bom` :pray:

**Comment by rickie** [comment]
I filed: https://github.com/square/okio/pull/1256.
