### ISSUE TITLE
Is exposing flush in Sink a good idea ?

### ISSUE THREAD

**Issue by pull-vert** [square/okio#1369]
`OutputStream.flush()` is only implemented in buffered output streams. Neither `FileOutputStream` or `Socket.SocketOutputStream` implement `flush()`, each write operation on both of them write directly in the file or the Socket. NIO's channels do not provide `flush()` for the same reason.

I think `flush()` operation in Okio is misleading because in most cases it does nothing on `Sink`, and nothing more than `emit()` in `BufferedSink`.

`Sink` implementations should not be based on buffered output streams, because `BufferedSink` is the way Okio does buffering, and double buffering should be avoided.

**Comment by JakeWharton** [comment]
There are plenty of times where flush makes sense. As soon as you start composing sinks `emit()` will be insufficient. For example, you could put a `GzipSink` around a `Sink` to a file, and buffer at both layers. In this case, a call to `emit()` would only push the bytes from the gzip layer to the buffer around the file sink. The buffering at both layers makes sense here because you want to buffer into the gzip operation, but you also want to buffer it's output so compressed data sufficiently accumulates before writing to the underlying file.

I wrote about the difference a while ago here: https://jakewharton.com/forcing-bytes-downward-in-okio/

Multiple layers of buffering in Okio are cheap. Unlike java.io, multiple layers of buffering do not perform copies but instead do moves. This means it's always safe for a function or class to accept a Sink, buffer it, and call emit to ensure bytes are not lost. As to whether that Sink was already buffered or not is a decision for the caller, and if it was they become responsible for additionally pushing the bytes down.

**Comment by pull-vert** [comment]
Thanks a lot @JakeWharton for this clear answer, I will also read your article with care. I'm closing this wrong issue !
