### ISSUE TITLE
Support file:// protocol in toPath()

### ISSUE THREAD

**Issue by padmalcom** [square/okio#1558]
First of all, thank you for this great library.

I use `toPath()` quite a lot to convert strings to `okio.Path`. My pain point is that I work with Uris a lot on android environments and thus, I frequently have protocol prefixes in my paths. It would be nice if `toPath()` would support at least the `file://` protocol.

**Comment by JakeWharton** [comment]
Android's Uri will give you the path component to then convert into an Okio path. Is that not enough? Supporting this would be akin to reimplementing Uri parsing because we still have to support dropping any credentials, hostname, port, query parameters, and fragments. I think it's best to leave that to a proper Uri class.

**Comment by padmalcom** [comment]
You are right, getting the path is sufficient.
