### ISSUE TITLE
Are there any plans for integration with NIO?

### ISSUE THREAD

**Issue by ksperling** [square/okio#197]
I'm mainly using Okio in the context of Wire and OkHttp, and have run into a few cases where NIO integration would be nice, for example viewing a ```ByteString``` as a ```ByteBuffer``` (fairly simply to hack up myself), or being able to adapt a ```{Readable,Writable}ByteChannel``` to the ```Buffered{Sink,Source}``` interface in a way that doesn't involve copying.

Implementing the BufferedSource/Sink interfaces directly is fairly complex of course as there are a lot of operations to implement, and there is really no way to implement buffer() without having the okio Buffer class aware of nio buffers.

It seems the key idea to make this work would be to have okio Buffer (or maybe a sub-class?) being able to treat a ByteBuffer as a Segment. Implementing Sink/Source for nio Channels then becomes pretty straightforward.

Is this something that's been considered and rejected, or is anything of this nature on the roadmap?

**Comment by swankjesse** [comment]
It’s definitely something we’ve considered. Unfortunately the NIO interfaces are pretty locked down; there’s no way to implement a custom NIO Buffer.

That leaves us with some other awkward options. Using NIO direct buffers for segments could be a win internally (due to strange shortcuts in OpenJDK’s java.io implementation) but it would probably not make sense in the API. The main value of Okio’s Buffer is that it grows; NIO buffers are sorely lacking that ability. With this we’d change how the Socket and File adapters work internally to use NIO’s APIs, if there turned out to be a performance benefit of doing that.

A completely different but also interesting option is to expose our own NIO-like constructs, without using the java.nio APIs formally. This is what Netty does with its EpollEventLoopGroup, which is cool but Linux only.

One thing to note - you should _never_ implement `BufferedSource` or `BufferedSink` manually. Instead implement `Source` or `Sink`, and use `Okio.buffer()` to do the rest.

**Comment by swankjesse** [comment]
No obvious action here.
