### ISSUE TITLE
RealBufferedSource available() always 0 before read()

### ISSUE THREAD

**Issue by kflan42** [square/okio#317]
From https://github.com/fabric8io/kubernetes-client/issues/843

If callers check for available before calling read, as one might do to avoid blocking, they will never read.

**Comment by JakeWharton** [comment]
That seems both like user error and spec compliant behavior. The docs for
InputStream explicitly stay the default returns 0 unconditionally.

What are you proposing?

**Comment by kflan42** [comment]
The docs say the method should be overriden and should return 0 at the end of the stream. The more I think about it the less I like available(), since either the implementer might need another thread to avoid blocking on an internal read or its return value may never change despite underlying bytes available being non-zero. I imagine only certain uses could make use of available's "estimate".

But InputStream doesn't make available() look very optional, at least not like Iterator.remove(). Throwing an UnsupportedOperationException in available() at least fails fast if used [incorrectly], though seems rather drastic. At present it will sometimes return the bytes left in the buffer after an internal read but usually just returns zero AFAICT.

Use of available() without knowledge of the underlying InputStream implementation would seem to be a code smell.

**Comment by JakeWharton** [comment]
The biggest problem from Okio's side is that it's (nearly) entirely
pull-based. So layers are never informing those higher up of availability.
We could potentially reach down into layers for something like
availability, but it's super easy for any layer to break that (also true of
InputStreams layering). I think methods like available() abandon the
pull-based nature of java.io.* and border on a hybrid push/pull approach.

One of the reasons Okio exists is because of the oddities of the java.io.*
APIs like InputStream and OutputStream like this one. It's actively hard to
interact with InputStream because there's not only more API surface, but it
has subtleties that can be unclear like this one. You're right about the
docs which is a bit weird because I don't see how it can NOT return 0 when
empty unless it blocks for a read.

**Comment by swankjesse** [comment]
Also note that InflaterInputStream can return 1 when 0 bytes are available. It's a bad API.
