### ISSUE TITLE
Allow reading strings of a certain length

### ISSUE THREAD

**Issue by ansman** [square/okio#319]
Currently you can either limit the length of a read string by the number of bytes or if you read lines you can limit the length but often you don't know the byte length of the string before writing it.

It would be nice if there was a method for reading a string with a given number of characters.

**Comment by JakeWharton** [comment]
Do you have a use case for this currently or is it theoretical? I'm worried
about chars vs. code points though.

**Comment by ansman** [comment]
I often use `Buffer` over Java's `ByteBuffer` to read and write streams of binary data.
Sometimes I want to write a String and then additional data. Now I have to first convert the String into a byte array, write the length and then the contents. It would be nice if you could skip converting it into bytes before writing it.

**Comment by cketti** [comment]
The string has to be converted to bytes anyway. Doesn't really matter who is doing it.
Writing/reading a (byte) length-prefixed string can already be comfortably accomplished using the public API.

```kotlin
fun BufferedSink.writeSizePrefixedString(string: String, charset: Charset) {
    val encodedString = ByteString.encodeString(string, charset)
    writeInt(encodedString.size())
    write(encodedString)
}

fun BufferedSource.readSizePrefixedString(charset: Charset): String {
    val byteCount = readInt().toLong()
    return readString(byteCount, charset)
}
```

**Comment by ansman** [comment]
@cketti yes, but the difference is that I need to convert a `byte[]` to hold the bytes while the `writeUtf8` will write it directly to the segment.

**Comment by cketti** [comment]
There's `Utf8.size()`.

> Returns the number of bytes used to encode string as UTF-8 when using ByteString.encodeUtf8 or Buffer.writeUtf8(String).

```kotlin
fun BufferedSink.writeSizePrefixedUtf8String(string: String) {
    writeInt(Utf8.size(string).toInt())
    writeUtf8(string)
}

fun BufferedSource.readSizePrefixedUtf8String(): String {
    val byteCount = readInt().toLong()
    return readUtf8(byteCount)
}
```

**Comment by ansman** [comment]
Hmm, interesting. It would require looping over the string twice but at least I wouldn't have to allocate a byte array. Thanks!

**Comment by cketti** [comment]
Using the value of `String.length()` and UTF-8 as encoding would be super weird. For a codepoint like U+1F369 you'd get a length of 2 because Java uses UTF-16 internally. But encoded as UTF-8 you get 4 bytes.
That means everyone who's reading the stream needs to know about UTF-16's surrogate pairs in order to be able to read the String.
It's also not immediately obvious how to deal with invalid length information and string pairs. E.g. a length of 2 with the code points U+0041 (1 Java char), U+1F369 (2 Java chars). You'd have to specify at which point a reader gives up and which bytes belong to the next entity to be read from the stream.

Bytes are easy. Use bytes :)
