### ISSUE TITLE
Organize project files according to Kotlin Multiplatform conventions

### ISSUE THREAD

**Issue by bnorm** [square/okio#584]
Once multiplatform changes settle down, would it be good to organize the project files based on the Kotlin Multiplatform conventions? I can make a series of commits that should allow git to track file moves for historical reference.

It was mentioned in a pull-request, wanted to keep a record of the thought and have a place for discussion.

**Comment by Egorand** [comment]
Yeah, I think we should do it. Navigating the project right now is awkward since the IDE doesn't highlight "modules" anymore (e.g. "js" is not highlighted as a source set, only "js/src/main"). Doesn't make sense to fight the MPP if we can move stuff into a structure it likes better without breaking Git history.

**Comment by swankjesse** [comment]
Make it so!
