### ISSUE TITLE
How to get Source from a file path in commonMain

### ISSUE THREAD

**Issue by VVictorWang** [square/okio#708]
Hi, I'm trying to use `okio-multiplatform` in my kotlin-multiplatform project for I/O. I'm wondering how can I get `Source` from a file path in commonMain? The examples provided are all getting `Source` from a jvm `File`. I mean, all examples provided only runs for jvm environment. So there's any way for us to operate file I/O in commonMain?

versions for `okio-multiplatform`: 2.5.0

**Comment by JakeWharton** [comment]
There is no way. For one it's unclear what we do in JS and WASM environments where access to files is far more encapsulated. If you're only doing Kotlin/JVM and Kotlin/Native you can expect/actual your own function for this.

Although I also don't believe we yet have a way to create a source from a file on native etiher...

**Comment by VVictorWang** [comment]
> There is no way. For one it's unclear what we do in JS and WASM environments where access to files is far more encapsulated. If you're only doing Kotlin/JVM and Kotlin/Native you can expect/actual your own function for this.
> 
> Although I also don't believe we yet have a way to create a source from a file on native etiher...

Thanks for replying. Is there any plan for supporting file system access in native platform such as windows and linux? It is possible to do that, we just need to encapsulate `Source` and `Sink` stream system based on posix file system interfaces.

**Comment by swankjesse** [comment]
Nothing firm.

It’s easy to build the core featues of a FileSystem abstraction: read, write, move, delete.

But the complexity of the rest is a series of investments that grow into a sizable project:
 - Directory traversal
 - Read & write metadata for POSIX Windows
 - Encodings of file names
 - Symlinks, hard links, canonical paths
 - Atomic vs. non-atomic file moves
 - File system capacity & limits
 - Special files like /dev/null and stdout
 - Pipes
 - Random access
 - Memory mapped files
 - Mechanisms to mount zip files

Also if we did it, we'd make sure the whole thing was friendly to testing. That makes the API a bit trickier because you need either `FileSystem.SYSTEM` or dependency injection.

There’s a bit of work on a FileSystem feature in kotlinx, but I’m worried they don’t value testing and may mess that part up.

**Comment by VVictorWang** [comment]
Thanks! Got the point, looking forward to `FileSystem` support in the future.
