### ISSUE TITLE
Read a file line-by-line from the end to the start

### ISSUE THREAD

**Issue by avently** [square/okio#713]
Hello. Looks like there is no way to read a file line-by-line from the end to the start of it. 
`source.readUtf8Line()` is terribly fast and would be really useful to have such method from your team which can do the same thing but from the end of the file. 
I have files that stores market trades and they are too big to read them from a start because I need only the latest trades that are on the end.

Could this method arrive to the lib or it isn't what you want to create?

**Comment by swankjesse** [comment]
This is surprisingly difficult to implement in Okio because we don’t have any abstractions that work backwards through a file. The closest we have is some code for performing random-access operations on a file in [this file](https://github.com/square/okhttp/blob/19771365f25d986d125478a75c15d24d6e285e12/okhttp/src/main/kotlin/okhttp3/internal/cache2/FileOperator.kt).

**Comment by avently** [comment]
@swankjesse 
>difficult to implement in Okio

Difficult but possible? I mean do you want to implement such thing in Okio or it's not gonna happen any time soon?
Because from my tests it's hard to make performance from MemoryMappedFile as good as Okio provides. And some developers could switch to your solution because it has a practical use-case for some industries like trading.

**Comment by swankjesse** [comment]
We're not going to add it. But if you'd like, try to use the linked class above to do it.

**Comment by avently** [comment]
Ok, Jesse, thanks for the answer. I'm closing the issue then.
