### ISSUE TITLE
Buffer.readString returns corrupted data

### ISSUE THREAD

**Issue by blackdigger1337** [square/okio#714]
Hi, I have faced the following issue with okio version 2.6.0.
When I use Buffer.readString after Buffer.writeString with a combination of other operations, it seems to return corrupted string.

Here is sample kotlin program
https://gist.github.com/blackdigger1337/1dd5f579dbb64175f41ec97e2b545890

it prints 
abc      9qqqq

and then

Exception in thread "main" java.io.EOFException
	at okio.Buffer.readLong(Buffer.kt:1168)
	at Test1Kt.main(test1.kt:25)
	at Test1Kt.main(test1.kt)

however it is expected to pring "abc"

**Comment by JakeWharton** [comment]
Okio is not a serialization format. Write string will write the string bytes but then the symmetric call to readString will read as many bytes as possible until EOF. You will need to write the length of the string before the string and then read the length and pass that value to readString to limit how far it goes.

**Comment by blackdigger1337** [comment]
thanks!
actually, I just came to that length solution, but thought there could be some better way.
okay :)

**Comment by JakeWharton** [comment]
Yeah Okio just has no opinion on the mechanism you use here because that's the responsibility of the layer of abstraction above Okio. You could use null-terminated strings and call `indexOf('\0')` and use that as the length, you could length-prefix, or you could use fixed-width. Okio just wants to get you the bytes, that's all.
