### ISSUE TITLE
Upgrade to Kotlin 1.3.71

### ISSUE THREAD

**Issue by f-lombardo** [square/okio#716]
People could experience problems in using in a Java project both okhttp and okio, since they declaredependence on different Kotlin versions. I think it would be a good idea to upgrade okio to Kotlin 1.3.71

**Comment by JakeWharton** [comment]
The standard library is fully compatible so we should never need to do this. In general we only want to bump the dependency when it's required which at this point is only to the latest multiple of .10 for Kotlin native users.

**Comment by f-lombardo** [comment]
I don't know Kotlin native at all, so I can't evaluate the impact of upgrading to 1.3.71 in this environment. Anyway I was guessing if it could be a problem for JVM users. IMHO, keeping Kotlin versions strictly aligned between okio and okhttp could be a good idea.

**Comment by JakeWharton** [comment]
If you're using a build system that does automatic version resolution it will never be a problem for the JVM. A library built against Kotlin 1.0.0 can use the very latest version of the stdlib because it promises to be binary and behaviorally compatible (within acceptable limits). This is similar to how you can run Okio on Java 14 despite that fact that we only compile with Java 8. The Kotlin standard library is very similar in that respect to the Java runtime library.

Thus, we generally don't do rolling upgrades of dependencies to keep them all in sync because there's no actual value to it. The only motivating factor for regular releases thus far based on Kotlin version is the (non-)compatibility of Kotlin/Native. And once that stabilizes, we will likely stop and go back to only upgrading and releasing when there's actual features and bug fixes.
